[package]
name = "dir_nav"
version = "0.1.0"
edition = "2018"
authors = ["Ragu Manjegowda <raghavendrahm0410@gmail.com>"]

[lib]
name = "dirnav"           # The name of the target.
path = "src/DirNav.rs"    # The source file of the target.

[dependencies]
