name: Text Finder CI

on:
    push:
        branches: [ main ]

    pull_request:
        branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
    test-workspace-root:
        runs-on: ubuntu-latest
        container:
            image: ragumanjegowda/docker:latest
            options: --user root -v ${{ github.workspace }}:/mnt/:rw
        steps:
            - uses: actions/checkout@v2

            - name: Update Rust
              run: rustup update

            - name: Test Cargo
              run: echo $CARGO_HOME && which cargo && cargo --version

            - name: Navigate to workspace root, Test format, Test clippy warnings
              run: |
                cd /mnt
                cargo build
                cargo fmt -- --check
                cargo clippy -- -Dwarnings

    test-cliparser:
        runs-on: ubuntu-latest
        container:
            image: ragumanjegowda/docker:latest
            options: --user root -v ${{ github.workspace }}:/mnt/:rw
        steps:
            - uses: actions/checkout@v2

            - name: Update Rust
              run: rustup update

            - name: Test Cargo
              run: echo $CARGO_HOME && which cargo && cargo --version

            - name: Navigate to cliparser, Test format, Test clippy warnings
              run: |
                cd /mnt/src/cliparser
                cargo fmt -- --check
                cargo clippy -- -Dwarnings

            - name: Navigate to cliparser, run tests
              run: |
                cd /mnt/src/cliparser
                cargo test --verbose tests::test_parameters -- --exact
                cargo test --verbose tests::test_parsing_empty -- --exact
                cargo test --verbose tests::test_parsing_non_empty -- --exact
                cargo test --verbose tests::test_parsing_invalid_key -- --exact
                cargo test --verbose tests::test_parsing_invalid_value -- --exact
                cargo test --verbose tests::test_parsing_duplicate -- --exact
                cargo test --verbose tests::test_parsing_set_key_value -- --exact

            - name: Navigate to cliparser, Run cliparser example app
              run: |
                cd /mnt/src/cliparser
                cargo run --verbose --example cli_parser_example_app

    test-dirnav:
        runs-on: ubuntu-latest
        container:
            image: ragumanjegowda/docker:latest
            options: --user root -v ${{ github.workspace }}:/mnt/:rw
        steps:
            - uses: actions/checkout@v2

            - name: Update Rust
              run: rustup update

            - name: Test Cargo
              run: echo $CARGO_HOME && which cargo && cargo --version

            - name: Navigate to dirnav, Test format, Test clippy warnings
              run: |
                cd /mnt/src/dirnav
                cargo fmt -- --check
                cargo clippy -- -Dwarnings

            - name: Navigate to dirnav, Test norecurse, Test recurse, Test search patterns
              run: |
                cd /mnt/src/dirnav
                cargo test --verbose tests::test_norecurse -- --exact
                cargo test --verbose tests::test_recurse -- --exact
                cargo test --verbose tests::test_searchpatterns -- --exact

            - name: Navigate to dirnav, Run dirnav example app
              run: |
                cd /mnt/src/dirnav
                cargo run --verbose --example dir_nav_example_app

    test-display:
        runs-on: ubuntu-latest
        container:
            image: ragumanjegowda/docker:latest
            options: --user root -v ${{ github.workspace }}:/mnt/:rw
        steps:
            - uses: actions/checkout@v2

            - name: Update Rust
              run: rustup update

            - name: Test Cargo
              run: echo $CARGO_HOME && which cargo && cargo --version

            - name: Navigate to display, Test format, Test clippy warnings
              run: |
                cd /mnt/src/display
                cargo fmt -- --check
                cargo clippy -- -Dwarnings

            - name: Navigate to display, run tests
              run: |
                cd /mnt/src/display
                cargo test --verbose tests::test_set_dir -- --exact
                cargo test --verbose tests::test_set_file -- --exact

            - name: Navigate to display, Run display example app
              run: |
                cd /mnt/src/display
                cargo run --verbose --example display_example_app

    test-textsearch:
        runs-on: ubuntu-latest
        container:
            image: ragumanjegowda/docker:latest
            options: --user root -v ${{ github.workspace }}:/mnt/:rw
        steps:
            - uses: actions/checkout@v2

            - name: Update Rust
              run: rustup update

            - name: Test Cargo
              run: echo $CARGO_HOME && which cargo && cargo --version

            - name: Navigate to textsearch, Test format, Test clippy warnings
              run: |
                cd /mnt/src/textsearch
                cargo fmt -- --check
                cargo clippy -- -Dwarnings

            - name: Navigate to textsearch, Test sets, Test traits
              run: |
                cd /mnt/src/textsearch
                cargo test --verbose tests::test_sets -- --exact
                cargo test --verbose tests::test_traits -- --exact

            - name: Navigate to textsearch, Run textsearch example app
              run: |
                cd /mnt/src/textsearch
                cargo run --verbose --example text_search_example_app
