name: Text Finder CI

on:
    push:
        branches: [ main ]

    pull_request:
        branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
    test-workspace-root:
        runs-on: ubuntu-latest
        container:
            image: ragumanjegowda/docker:latest
            options: --user root -v ${{ github.workspace }}:/mnt/:rw
        steps:
            - uses: actions/checkout@v2

            - name: Update Rust
              run: rustup update

            - name: Test Cargo
              run: echo $CARGO_HOME && which cargo && cargo --version

            - name: Navigate to workspace root, Test format, Test clippy warnings
              run: |
                cd /mnt
                cargo build
                cargo fmt -- --check
                cargo clippy -- -Dwarnings

    test-dirnav:
        runs-on: ubuntu-latest
        container:
            image: ragumanjegowda/docker:latest
            options: --user root -v ${{ github.workspace }}:/mnt/:rw
        steps:
            - uses: actions/checkout@v2

            - name: Update Rust
              run: rustup update

            - name: Test Cargo
              run: echo $CARGO_HOME && which cargo && cargo --version

            - name: Navigate to dirnav, Test format, Test clippy warnings
              run: |
                cd /mnt/dirnav
                cargo fmt -- --check
                cargo clippy -- -Dwarnings

            - name: Navigate to dirnav, Test norecurse, Test recurse, Test search patterns
              run: |
                cd /mnt/dirnav
                cargo test --verbose tests::test_norecurse -- --exact
                cargo test --verbose tests::test_recurse -- --exact
                cargo test --verbose tests::test_searchpatterns -- --exact

            - name: Navigate to dirnav, Run dirnav example app
              run: |
                cd /mnt/dirnav
                cargo run --verbose --example dir_nav_example_app

    test-textsearch:
        runs-on: ubuntu-latest
        container:
            image: ragumanjegowda/docker:latest
            options: --user root -v ${{ github.workspace }}:/mnt/:rw
        steps:
            - uses: actions/checkout@v2

            - name: Update Rust
              run: rustup update

            - name: Test Cargo
              run: echo $CARGO_HOME && which cargo && cargo --version

            - name: Navigate to textsearch, Test format, Test clippy warnings
              run: |
                cd /mnt/textsearch
                cargo fmt -- --check
                cargo clippy -- -Dwarnings

            - name: Navigate to textsearch, Test sets, Test traits
              run: |
                cd /mnt/textsearch
                cargo test --verbose tests::test_sets -- --exact
                cargo test --verbose tests::test_traits -- --exact

            - name: Navigate to textsearch, Run textsearch example app
              run: |
                cd /mnt/textsearch
                cargo run --verbose --example text_search_example_app
